### PR TITLE
fix: results for ts 4.2+

### LINKED ISSUE #20: Failed to work on TypeScript 4.2
I have reported to the TypeScript team but they say this is not a bug in TypeScript.

https://github.com/microsoft/TypeScript/issues/43098

### PR DESCRIPTION
**Pull request by Jack-Works**
hi! @vultix

I have fixed this library on typescript 4.2+. But I only fix the `Result` `Ok` `Err` part. `Option`, or rxjs support is still breaking.

This will fix #20

### CODE REVIEW

**Comment by Jack-Works** [comment]
ping @vultix hello!

**Comment by vultix** [comment]
@Jack-Works This PR still doesn't seem to fix the code snippet you provided in #20 

This still won't compile
```typescript
declare const result: Result<string, void>;
result.andThen((x) => (x === '' ? Ok('empty') : Err(undefined))).unwrapOr(undefined);
```

**Comment by Jack-Works** [comment]
Oops, sad. But at least it passes all (non rxjs) test in the repo

**Comment by Jack-Works** [comment]
Well, I did a little more try on this but found it's quite not possible to make things working.

**Comment by Jack-Works** [comment]
Another possible way to do this is, write definitions (.d.ts only) and once it works (will it?), we implement those types in JS

**Comment by vultix** [comment]
After spending ages playing around with it, I think I have a fix.  I'll try to get it out after work today

**Comment by vultix** [comment]
Sorry this took so long.  My supposed fix didn't work.  I've found time to work on it some more and finally found something I'm happy with!

**Comment by vultix** [comment]
@Jack-Works This is out in npm now

**Comment by Jack-Works** [comment]
thanks! although there is still 1 case breaking but that's easy to fix.

**Pull request merged**
