### PR TITLE
Enhances

### LINKED ISSUE #3: Can I create a Err / Ok without new?
The new operator seems doesn't important

### LINKED ISSUE #4: TS2349: This expression (Result<?, ?>.else) is not callable
Code:
```ts
declare function work(): Result<boolean, void>
work().else(true)
// And I think it should accept a function as well `.else(() => heavyWork())`
```

Error:
```
(property) else: (<T2>(val: T2) => boolean) | (<T2>(val: T2) => T2)

This expression is not callable.

Each member of the union type
        '(<T2>(val: T2) => boolean) | (<T2>(val: T2) => T2)' has signatures,
but none of those signatures are compatible with each other.(2349)
```
[Playground link](https://www.typescriptlang.org/play/?target=6&ssl=1&ssc=1&pln=46&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHccYBrACgEoAueAJRAGdkIMAeAIxxwhClQBp4ANxxZgAPgCwAKCKlKAOhAQGIMhhjIQFGTJAAPAA7EM8UJFgILDBvACiMGKzvj4Abxnwv8OFGB4IAE9hKAgaOwBuT28GDChsMB9ef1Qg+wBZAAUAFQBNcMdWETFxKOlvJL8A4JwSeABeJFDVMorfFLSQRwb4DS1W7zA8WM1MYjIhUPCKAa8AegAqBejvBfgASURegAsEOCYWeG2oWygQiC0kjGQYVFsMY9NJi5AFLwB5B66CLFUrm7uOwQhhOqmA8Cw+GeWgUKy8awAAiCYFAALbnIHnS4YHBJQzQMAIL7wLowYiELAPOHwBZzOHKVSsbIAJnEEym8BZ1E5zNmJKM4AwZFRDAA5jQRpDRdzUCAhF0+WgCCjDJQaLL5TA+aioIYmazhbrDF0aOywvANV0KA1XFyCk4XNrdQ4HQadYZjTBTaTpjb7MzuS7nKyygBfPRGExmcDQODway2d4kJmuDzlbztarnGjZPmxeJYRKZ1LBOxZPI0JNFUQSPnFtK1Hp9EB15JZ0k9RDNFtwoZ3PpjGBmnMzOGLZbp1YbLbE-bMUzHU5YvYga63e6PZdveCfXYwH5-OBrwHEkE2EDgyFb6mI5FojHE6FE3FwfFQQmY0nkn5Uyfwul-gyID6myzw5gGOZ8gYxqYMKYoShoUrcrmcJKiqaqck6eosmy7qeqaYGcta9S2hBO7JjhWFBnYbpGia8BkD6Fpylafo0dyVbZKUMjhtI0FRuYsZEoExp0Iw85MoILg9GQnGuAAPvYhQuNaABk7hwu6IGGh69HDkRfp2mJBxsCyUncX+7rUbRulegxhF2MRrjsTQ9AmZJ-oWaGZT8TApiCZYvQiQgbnzkm2TBUy-IYCAqDALYoUsKwfCBIIKXiK4jTZNFsXxcZEmQogXTwAAqmlqCBK4AD8pXwOqLFahGxh+dGFhxhgwX5SwLoRcaUUGDFcUJeJSUpeVlWZZyOVDV1bBjRCqBFTApXVbV9Waj5kYtQFcYoOg2B4LNDBMgAjFJZ08lJBpziwJ2uSNpkXXYJ3iIIN0YMy93uWZnncolbAANrZBdLIALrnfAik0RZvn+TGgV7ZguD4P9x3A+dgg-TRmMAMxSTjbLvXds2nedr1JCZn0k1jrJvQ9ONfRJ2R4-YBN-Q9rBAyDzK4+D9gnZD-qC3YBObc1cNtQgiMHSjD1o093NXbj+OYwALFJquEw9xP-aT-Pk+9VO6zTBv04zSXM-jpsmar5umer9ia+z7lc5jPOciz2Sq3zz3C8yws48LmtiwJ8O7WgSOHajZAKLH70MHbyUVeN4gA6DzsSSlacp2UQA)

### LINKED ISSUE #8: .map works strange
I have two functions:

```ts
extractTextFromTypedMessage(x: Message | null): Result<string, E1>
shouldActivate(post: string): Result<void, E2>
```

Then I write
```
extractTextFromTypedMessage(post).map(shouldActivate)
```

What I expect is unpack the map returned by should activate:
```
Result<void, E1 | E2>
```

But it finally returns
```
Result<Result<void, E2>, E1>
```

### PR DESCRIPTION
**Pull request by Jack-Works**
- chore: upgrade dependencies
- chore: cleanup code
- test: write test for main function
- fix #4 (TS2349: This expression (Result<?, ?>.else) is not callable)
- close #3 (Call without `new`, Now it is possibe to easily transfrom Promise into checked exception `promise.then(Ok, Err)`)
- close #8 (Implement `andThen` in Rust)
- fix: Results type on 0 or 1 args
- feat: impl `Symbol.iterator` for Ok
- feat: add a new helper `wrap` (`wrap(() => fnMayThrowError())`) to convert `try-catch` style in to checked exception
- feat: add a new helper `any`. (`Results`(`all`) compare to `any`)
- feat: add `safeUnwrap` (`into_ok` in Rust) that unwrap in the compile time.

### CODE REVIEW

**Comment by vultix** [comment]
@Jack-Works Thank you for your contributions!  I may not have time to review this until the weekend, but I'm excited to take a look.

**Comment by Jack-Works** [comment]
@vultix hi?

**Comment by tom-sherman** [comment]
Symbol.iterator is interesting, what problem does this solve?

**Comment by tom-sherman** [comment]
Can I suggest you move these features out into seperate PRs? Bundled together it's almost impossible to review.

**Comment by Jack-Works** [comment]
Hmm those features aren't added one-by-one. I guess, the main file is not too long. You can review the whole file, or commit-by-commit. I'm sorry for that 😅

**Comment by tom-sherman** [comment]
Ok, well that is probably one of the reasons why this hasn't been reviewed yet.

**Comment by Jack-Works** [comment]
@vultix ping hi! 🙈

**Comment by vultix** [comment]
@Jack-Works I'm sorry for taking so long on this.  I'm going to go ahead and merge this into master, do some cleanup work, and then make a release later today.

**Pull request merged**
